# Define the namespaces for data farming jobs.

# NCAAF - College Football
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: americanfootball-ncaaf
  name: americanfootball-ncaaf
---
# NFL - National Football League
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: americanfootball-nfl
  name: americanfootball-nfl
---

