# Define jobs that run to completion.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: americanfootball-ncaaf-american
  namespace: americanfootball-ncaaf
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: americanfootball-ncaaf-decimal
              image: alpine
              command: ["date"]
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: americanfootball-ncaaf-decimal
  namespace: americanfootball-ncaaf
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: americanfootball-ncaaf-decimal
              image: alpine
              command: ["date"]
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: americanfootball-nfl-american
  namespace: americanfootball-nfl
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: americanfootball-nfl-american
              image: alpine
              command: ["date"]
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: americanfootball-nfl-decimal
  namespace: americanfootball-nfl
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: americanfootball-nfl-decimal
              image: alpine
              command: ["date"]
          restartPolicy: Never
